Update repo documentation
qbicsoftware/data-model-lib pull request #286
Opened 2022-02-08 10:04 UTC by jenniferboedker

2022-02-08 11:15 UTC, Steffengreiner requested changes
Nicely done! I found some minor typos in the Readme but nothing major. 
However I see that there are still 16 branches on this repo (mostly dependabot). 
Maybe this could also be resolved? 
Additionally the workflows are not in sync with the one outlined in the [template](https://github.com/qbicsoftware/spring-boot-rest-service-template/tree/main/.github/workflows). 
(delete generate-reports.yml, dependabot.yml and adapt naming to the one suggested in the template)

2022-02-08 11:15 UTC, Steffengreiner commented on README.md
> +##Overview:
Missing Space leads to showing the markdown code instead of the formatted result
```suggestion
## Overview:
```

2022-02-08 11:15 UTC, Steffengreiner commented on README.md
> +
```suggestion
```

2022-02-08 11:15 UTC, Steffengreiner commented on README.md
> +  <version>version-number</version-number>
```suggestion
  <version>version-number</version>
```

2022-02-08 11:49 UTC, jenniferboedker commented on .github/release.yml
> +          MAVEN_REPO_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
```suggestion
          MAVEN_REPO_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          
```

2022-02-08 13:48 UTC, Steffengreiner submitted a review, later dismissed
Nicely Done! 👍

2022-02-09 11:30 UTC, Steffengreiner requested changes
Nearly Done 🥉, however there are still some really minor issues :  
1.) You still have to remove the outdated workflows "java-checkstyle.yml" and "changelog-update.yml"
2.) Adapt release.yml 

Also maybe we need to check if we need to add the the 3rd party everit package to the license section .

2022-02-09 11:30 UTC, Steffengreiner commented on .github/release.yml
> +      - JohnnyQ5
See newest release.yml of [template](https://github.com/qbicsoftware/spring-boot-rest-service-template/blob/main/.github/release.yml)](github-actions)
```suggestion
      - JohnnyQ5
      - github-actions
```

2022-02-09 13:11 UTC, jenniferboedker commented
I think there is nothing wrong with checking the style

2022-02-10 08:04 UTC, jenniferboedker commented
see #287

2022-02-10 08:04 UTC, closed without merging